### ISSUE TITLE
Drawing not clipped to area bounds

### ISSUE THREAD

**Issue by jeffgrann** [globulus/swiftui-digital-signature#1] opened 2021-12-27 19:46 UTC
The user can draw outside of the signature area.

**Comment by gordan-glavas-codecons** [comment] 2021-12-30 09:22
Hi Jeff,

the issue is fixed in v.0.1.1.

Thanks for collaborating!

**Closed as completed by gordan-glavas-codecons** 2021-12-30 09:22 UTC

**Comment by jeffgrann** [comment] 2021-12-30 15:37
Thanks!
